version: '3'
services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - .:/src
      - ~/.gitignore:/root/.gitignore
      - ~/.gitignore_global:/root/.gitignore_global
    ports:
      - 5000:5000
  dynamo:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -dbPath /data
    volumes:
      - ./data:/data
      - ~/.gitignore:/root/.gitignore
      - ~/.gitignore_global:/root/.gitignore_global
    ports:
      - 8000:8000
